# Generated by Django 5.2.7 on 2025-12-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_museumcomment'),
        ('museum', '0008_alter_bookmark_unique_together_booking'),
    ]

    operations = [
    ]
